### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by kentsommer** [ColumbiaDVMM/Transform_Covariant_Detector#1]
Hi all,

Just wondering if you had a timeline for the release of the implementation? Paper is fascinating and I'm just eager to be able to experiment with it :+1:

**Comment by spongezhang** [comment]
Thank you for your interest in our work. The code and the document should be ready by the end of this month. Will let you know. :)

**Comment by kentsommer** [comment]
Awesome @spongezhang, I'm looking forward to it! :+1:
