### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by Miranda0920** [ColumbiaDVMM/Transform_Covariant_Detector#5]
When i try to run the file batch_run_test.sh, an error occur:
./batch_run_test.sh : line 5 : /home/xuzhang/MATLAB/bin/matlab:no such file or directory

Is the code incomplete? Or what file should i add somewhere?

**Comment by spongezhang** [comment]
Hi, 

That's that matlab executive file. You should change that file according to your system.

Best,
