### ISSUE TITLE
Selection of scale for matching score

### ISSUE THREAD

**Issue by NehalD99** [ColumbiaDVMM/Transform_Covariant_Detector#7]
Hello,

In the evaluation framework for matching score, is the scale of the feature points extracted from your CNN detector have a fixed value or it is taken from the scale space pyramid ?

Thanks,
Nehal

**Comment by spongezhang** [comment]
Hi Nehal,

Sorry for the late reply. 

We created a pyramid and extract feature points from multi-scale pyramid. See line 187 in patch_network_point_test.py

`pyramid = pyramid_gaussian(img, max_layer = 4, downscale=np.sqrt(2))`

Best,
Xu
